name: ASP.NET Build, Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches all history for GitVersion
      
      # .NET Setup and Build Steps
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build solution
        run: dotnet build --configuration Release --no-restore
      
      # Run Tests
      - name: Run unit tests
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./TestResults
      
      # Code Coverage Report
      - name: Generate code coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: './TestResults/**/coverage.cobertura.xml'
          targetdir: './CoverageReport'
          reporttypes: 'HtmlInline_AzurePipelines;Cobertura'
          
      - name: Upload code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: './CoverageReport'
          
      # Create Environment Files
      - name: Create env files from secrets
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env.production
          echo "${{ secrets.ENV_DEVELOPMENT }}" > .env
          # Verify files were created
          ls -la .env*
      
      # Docker Setup and Build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      # Code Quality Analysis
      - name: Run code analysis
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSHARP: true
      
      # Create deployment artifact BEFORE Docker build
      - name: Publish web project
        run: dotnet publish ArtGallery.WebAPI/ArtGallery.WebAPI.csproj -c Release -o ./publish
      
      # Build and Push Docker Images
      - name: Build and push Docker images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          # Create certificates directory if needed
          mkdir -p certificates
          
          # Use 'docker compose' instead of 'docker-compose'
          docker compose -f docker-compose.github.yml build
          docker compose -f docker-compose.github.yml push
      
      # Check for SQL migrations
      - name: Check for pending migrations
        run: |
          # Install EF Core tools if not present
          dotnet tool install --global dotnet-ef || true
          # Check migrations
          dotnet ef migrations list --project ArtGallery.Persistence --startup-project ArtGallery.WebAPI || echo "No migrations found or EF tools not configured"
      
      # Output Build Information
      - name: Add build summary
        if: success()
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "* **Project**: ArtGallery ASP.NET Application" >> $GITHUB_STEP_SUMMARY
          echo "* **Version**: $(grep -m 1 '<Version>' ArtGallery.WebAPI/*.csproj | sed 's/.*<Version>\(.*\)<\/Version>.*/\1/' || echo 'Unknown')" >> $GITHUB_STEP_SUMMARY
          echo "* **Build Number**: ${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "* **Image**: ${{ secrets.DOCKER_HUB_USERNAME }}/artgallery.webapi:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
      
      # Upload deployment artifact
      - name: Upload deployment artifact
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ./publish
          
      # Notification on completion
      - name: Notify on completion
        if: always()
        run: |
          status="${{ job.status }}"
          if [ "$status" == "success" ]; then
            echo "## ✅ Workflow completed successfully" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ❌ Workflow failed" >> $GITHUB_STEP_SUMMARY
          fi
