name: Docker Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env files from secrets
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env.production
          echo "${{ secrets.ENV_DEVELOPMENT }}" > .env
          # Verify files were created
          ls -la .env*

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          # Create certificates directory if needed
          mkdir -p certificates
          
          # Use 'docker compose' instead of 'docker-compose'
          docker compose -f docker-compose.github.yml build
          docker compose -f docker-compose.github.yml push
