name: Docker Build and Deploy

on:
  push:
    branches: [ master ]  # Using master branch as specified
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env files from secrets
        run: |
          # Create .env.production file from secrets
          echo "${{ secrets.ENV_PRODUCTION }}" > .env.production
          
          # Create .env file for development if needed
          echo "${{ secrets.ENV_DEVELOPMENT }}" > .env
          
          # Verify files were created (don't show content in logs)
          ls -la .env*

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
        run: |
          docker-compose -f docker-compose.github.yml build
          docker-compose -f docker-compose.github.yml push
          
      - name: Deploy with docker-compose
        env:
          JWT_KEY: ${{ secrets.JWT_KEY }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
        run: |
          # Deploy using docker-compose
          docker-compose -f docker-compose.yml up -d
